In [85]:
import pandas as pd
import numpy as np

## Q1. Pandas version

What version of Pandas did you install?

In [4]:
print(pd.__version__)

3.0.2

In [6]:
# Read pandas from internet
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head(3)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341

## Q2. How many records in the dataset?

In [ ]:
# method 1 just to get the shape
nr_of_records = df.shape[0]
nr_of_columns = df.shape[1]
print("Nr_of_records:", nr_of_records)

Nr_of_records: 9704

In [16]:
# method 2 to get the length
len(df)

9704

In [17]:
print("Maximum number of non-nan entries: ", df.count().max())
print("Minimum number of non-nan entries: ", df.count().min())

Maximum number of non-nan entries:  9704
Minimum number of non-nan entries:  8774

## Q3. Fuel types
How many fuel types present in the dataset?

In [18]:
df.head(2)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217

In [ ]:
# gives just a number of unique items
df.loc[:,'fuel_type'].nunique()

2

In [ ]:
# Gives a bit more information about the unique items
df.loc[:,'fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

## Q4. Missing values
How many columns in the dataset have missing values?

In [32]:
(df.isnull().sum() > 0).sum()

np.int64(4)

In [34]:
df.isna().any().sum()

np.int64(4)

In [ ]:
columns_with_nan = df.columns[df.isna().any()].tolist()
columns_with_nan

['num_cylinders', 'horsepower', 'acceleration', 'num_doors']

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [54]:
df[df['origin'].str.lower() == 'asia'].loc[:,'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower

In [56]:
df['horsepower'].median()

np.float64(149.0)

In [66]:
tmp = df['horsepower'].value_counts().items()
value, counts = next(tmp)
print(f"Most common value is: {value} with nr of counts {counts}")

Most common value is: 152.0 with nr of counts 142

In [71]:
a = df['horsepower'].mode()[0]
a

np.float64(152.0)

In [74]:
new_median = df['horsepower'].fillna(a).median()

In [75]:
print(f"Median before filling in nan: {df['horsepower'].median()}")
print(f"Median after filling in nan: {new_median}")

Median before filling in nan: 149.0
Median after filling in nan: 152.0

In [81]:
tmp_df = df[(df['origin'].str.lower()=="asia")].loc[:,['vehicle_weight','model_year']].iloc[:7]
tmp_df

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [89]:
X = tmp_df.values
X.shape

(7, 2)

In [105]:
XTX = X.T @ X
print(XTX.shape)
print(XTX)

(2, 2)
[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]

In [110]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv.shape)
print(XTX_inv)

(2, 2)
[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]

In [111]:
y = np.array([1100,1300,800,900,1000,1100,1200])
y.shape

(7,)

In [117]:
w = (XTX_inv @ X.T @ y)
w.shape

(2,)

In [118]:
w.sum()

np.float64(0.5187709081074016)